version: '3.8'

services:
  backend:
    build: ./backend
    container_name: thinkboard-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    container_name: thinkboard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

